In [4]:
import pandas as pd

In [5]:
pip install beautifulsoup4

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (4.11.1)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4) (2.3.1)
Note: you may need to restart the kernel to use updated packages.

In [6]:
from bs4 import BeautifulSoup

In [7]:
soup = BeautifulSoup("<p>Some<b>bad<i>HTML")

In [8]:
print(soup.prettify())

<html>
 <body>
  <p>
   Some
   <b>
    bad
    <i>
     HTML
    </i>
   </b>
  </p>
 </body>
</html>

In [9]:
from flask import Flask, Response
import requests

In [10]:
base_url = "https://www.airlinequality.com/airline-reviews/british-airways"
pages = 10
page_size = 100

reviews = []

# for i in range(1, pages + 1):
for i in range(1, pages + 1):

    print(f"Scraping page {i}")

    # Create URL to collect links from paginated data
    url = f"{base_url}/page/{i}/?sortby=post_date%3ADesc&pagesize={page_size}"

    # Collect HTML data from this page
    response = requests.get(url)

    # Parse content
    content = response.content
    parsed_content = BeautifulSoup(content, 'html.parser')
    for para in parsed_content.find_all("div", {"class": "text_content"}):
        reviews.append(para.get_text())

    print(f"   ---> {len(reviews)} total reviews")

Scraping page 1
   ---> 100 total reviews
Scraping page 2
   ---> 200 total reviews
Scraping page 3
   ---> 300 total reviews
Scraping page 4
   ---> 400 total reviews
Scraping page 5
   ---> 500 total reviews
Scraping page 6
   ---> 600 total reviews
Scraping page 7
   ---> 700 total reviews
Scraping page 8
   ---> 800 total reviews
Scraping page 9
   ---> 900 total reviews
Scraping page 10
   ---> 1000 total reviews

In [11]:
df = pd.DataFrame()
df["reviews"] = reviews
df.head()

                                             reviews
0  ✅ Trip Verified |  I will never travel with Br...
1  ✅ Trip Verified |  I am already in Portugal so...
2  ✅ Trip Verified |  Terrible. Avoid this airlin...
3  ✅ Trip Verified |  Despite being a gold member...
4  Not Verified | Regarding the aircraft and seat...

In [12]:
df.to_csv("D:\Repositories\BA_reviews.csv")

In [13]:
pwd

'D:\\Repositories\\Data-Science'

In [14]:
data = pd.read_csv("D:\Repositories\BA_reviews.csv")

In [15]:
data.columns

Index(['Unnamed: 0', 'reviews'], dtype='object')

In [16]:
data.columns

Index(['Unnamed: 0', 'reviews'], dtype='object')

In [17]:
data

     Unnamed: 0                                            reviews
0             0  ✅ Trip Verified |  I will never travel with Br...
1             1  ✅ Trip Verified |  I am already in Portugal so...
2             2  ✅ Trip Verified |  Terrible. Avoid this airlin...
3             3  ✅ Trip Verified |  Despite being a gold member...
4             4  Not Verified | Regarding the aircraft and seat...
..          ...                                                ...
995         995  ✅ Trip Verified |  Had four flights in total w...
996         996  ✅ Trip Verified |  Johannesburg to Heathrow. B...
997         997  ✅ Trip Verified |  The queue for bag drop was ...
998         998  ✅ Trip Verified |  British Airways changed pla...
999         999  ✅ Trip Verified |  Mumbai to Edinburgh via Lon...

[1000 rows x 2 columns]

In [18]:
data.dropna()

     Unnamed: 0                                            reviews
0             0  ✅ Trip Verified |  I will never travel with Br...
1             1  ✅ Trip Verified |  I am already in Portugal so...
2             2  ✅ Trip Verified |  Terrible. Avoid this airlin...
3             3  ✅ Trip Verified |  Despite being a gold member...
4             4  Not Verified | Regarding the aircraft and seat...
..          ...                                                ...
995         995  ✅ Trip Verified |  Had four flights in total w...
996         996  ✅ Trip Verified |  Johannesburg to Heathrow. B...
997         997  ✅ Trip Verified |  The queue for bag drop was ...
998         998  ✅ Trip Verified |  British Airways changed pla...
999         999  ✅ Trip Verified |  Mumbai to Edinburgh via Lon...

[1000 rows x 2 columns]

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1000 non-null   int64
 1   reviews     1000 non-null   object
dtypes: int64(1), object(1)
memory usage: 15.8+ KB

In [20]:
import nltk

In [21]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Abhin\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [22]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [23]:
sid = SentimentIntensityAnalyzer()

In [24]:
data.iloc[0]['reviews']

'✅ Trip Verified |  I will never travel with British Airways again. I spent over $10,000 on a business class seat to attend a funeral in the UK. First, the Boeing 787-9 cabin has 7 seats across the aisle so what you are getting in reality is premium economy. The seats are narrow and effectively are a business class seat cut in half. They have squeezed these seats in which means that some passengers bump their heads into the bulkhead when they stand up and many have to clamber over others to go to the toilet, which wakes up that passenger. The whole point about business class is that you pay to rest and have privacy and not have someone push over the top of you. Second, the food was disgusting. Third, the service terrible. Fourth, the toilet was tiny. Fifth, the inflight screen was fixed and too high so I could not see anything. Sixth, their baggage handling is also appalling meaning that my taxi was waiting for 2 hours and I had to pay more (no free airport transfers with British Airways). Seventh, the charging points did not work. The second leg to London was on a larger plane with 4 seats across the aisle. That was bearable because no hopping over people but the seat was very uncomfortable because it was not one piece. This means that you are sleeping on a metal bar (the seat) where there is a gap in the seat. To add insult to injury I now find that both flights back to Sydney are on the small plane. To book a seat before check in is $170. I paid it but note that there were only 4 seats left. This is why I got the worst seat in the house going out. This is the most appalling airline service I have ever encountered. There is no point paying for business class in British Airways. '

In [25]:
sid.polarity_scores(data.iloc[0]['reviews'])

{'neg': 0.113, 'neu': 0.869, 'pos': 0.017, 'compound': -0.9824}

In [26]:
data['scores'] = data['reviews'].apply(lambda reviews: sid.polarity_scores(reviews))

In [27]:
data.head()

,Unnamed: 0,reviews,scores
0,0,✅ Trip Verified | I will never travel with Br...,"{'neg': 0.113, 'neu': 0.869, 'pos': 0.017, 'co..."
1,1,✅ Trip Verified | I am already in Portugal so...,"{'neg': 0.109, 'neu': 0.856, 'pos': 0.035, 'co..."
2,2,✅ Trip Verified | Terrible. Avoid this airlin...,"{'neg': 0.171, 'neu': 0.829, 'pos': 0.0, 'comp..."
3,3,✅ Trip Verified | Despite being a gold member...,"{'neg': 0.159, 'neu': 0.784, 'pos': 0.057, 'co..."
4,4,Not Verified | Regarding the aircraft and seat...,"{'neg': 0.1, 'neu': 0.814, 'pos': 0.086, 'comp..."

In [28]:
data['compound'] = data['scores'].apply(lambda d:d['compound'])

In [29]:
data.head()

,Unnamed: 0,reviews,scores,compound
0,0,✅ Trip Verified | I will never travel with Br...,"{'neg': 0.113, 'neu': 0.869, 'pos': 0.017, 'co...",-0.9824
1,1,✅ Trip Verified | I am already in Portugal so...,"{'neg': 0.109, 'neu': 0.856, 'pos': 0.035, 'co...",-0.5719
2,2,✅ Trip Verified | Terrible. Avoid this airlin...,"{'neg': 0.171, 'neu': 0.829, 'pos': 0.0, 'comp...",-0.8519
3,3,✅ Trip Verified | Despite being a gold member...,"{'neg': 0.159, 'neu': 0.784, 'pos': 0.057, 'co...",-0.8680
4,4,Not Verified | Regarding the aircraft and seat...,"{'neg': 0.1, 'neu': 0.814, 'pos': 0.086, 'comp...",-0.4541

In [30]:
data['comp_score'] = data['compound'].apply(lambda score: 'pos' if score >=0 else 'neg')

In [31]:
data.head()

,Unnamed: 0,reviews,scores,compound,comp_score
0,0,✅ Trip Verified | I will never travel with Br...,"{'neg': 0.113, 'neu': 0.869, 'pos': 0.017, 'co...",-0.9824,neg
1,1,✅ Trip Verified | I am already in Portugal so...,"{'neg': 0.109, 'neu': 0.856, 'pos': 0.035, 'co...",-0.5719,neg
2,2,✅ Trip Verified | Terrible. Avoid this airlin...,"{'neg': 0.171, 'neu': 0.829, 'pos': 0.0, 'comp...",-0.8519,neg
3,3,✅ Trip Verified | Despite being a gold member...,"{'neg': 0.159, 'neu': 0.784, 'pos': 0.057, 'co...",-0.8680,neg
4,4,Not Verified | Regarding the aircraft and seat...,"{'neg': 0.1, 'neu': 0.814, 'pos': 0.086, 'comp...",-0.4541,neg

In [32]:
data['comp_score'].describe()

count     1000
unique       2
top        pos
freq       533
Name: comp_score, dtype: object

In [39]:
x = data ['reviews'].rsplit('|',1)

AttributeError: 'Series' object has no attribute 'rsplit'